### PR TITLE
fix for when multiple configs are exported

### LINKED ISSUE #49: Doesn't appear to work with multiple configs being exported
This plugin doesn't appear to work when multiple configs are exported. For example, in `webpack.config.js`:

```js
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const WasmPackPlugin = require("@wasm-tool/wasm-pack-plugin");

module.exports = ["pkg1", "pkg2"].map(pkg=> ({
  entry: path.resolve(__dirname, pkg, "index.js"),
  output: {
    path: path.resolve(__dirname, "dist", pkg),
    filename: "bundle.js"
  },
  plugins: [
    new HtmlWebpackPlugin(),
    new WasmPackPlugin({
      crateDirectory: path.resolve(__dirname, pkg)
    }),
  ]
}));
```

Docs on exporting multiple configs: https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations

Exporting multiple configs is useful when working in workspaces that should produce multiple `.wasm` files, like a project with a bunch of examples.

### PR DESCRIPTION
**Pull request by liamcurry**
Closes #49 and bumps the version to `0.2.2`

### CODE REVIEW

File: plugin.js [hunk 1]
```diff
@@ -9,16 +9,15 @@ const Watchpack = require('watchpack');
...
-
 class WasmPackPlugin {
   constructor(options) {
+    /**
+     * In some cases Webpack will require the pkg entrypoint before it actually
+     * exists. To mitigate that we are forcing a first compilation.
+     *
+     * See https://github.com/wasm-tool/wasm-pack-plugin/issues/15
+     */
+    this.ranInitialCompilation = false;
```
Comment (xtuc) [inline plugin.js]: I would use `_ranInitialCompilation` by convention here, could you please rename it?

Comment (liamcurry) [reply plugin.js]: Updated

**Comment by xtuc** [comment]
Thanks for your PR, I published `@wasm-tool/wasm-pack-plugin@0.2.2`.
